version: '3.8'
services: 
  
  #nginx.app.localhost 
  
  #apache.app.localhost
  
  traefik: 
    image: traefik:v2.3.6  #localhost:8080 insecure
    labels: 
      - "traefik.http.routers.api.rule=Host(`traefik.app.test`)"  #add traefik.app.test in /etc/hosts before
      - "traefik.http.routers.api.service=api@internal"

      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:{SHA}fEqNCco3Yq9h5ZUglD3CZJT4lBs=" # user: admin pass:123456
      
    ports: 
      - 80:80
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
    networks: 
      traefik_network:
networks: 
  traefik_network:
    name: traefik_net
    driver: bridge
    ipam: 
      driver: default      
